In the FutureRepyExceptionHierarchy, [wiki:LocalIPChanged] occurs when the repy program calls `getconnection()` or `getmessage()`.